// 语义图标表:延续旧 renderer 的 data-icon 名称,映射到 lucide-react。
// 组件按名字取图标,保持与旧 UI 相同的视觉语义(stroke 风格 1.8px)。

import {
  AlignLeft,
  AlertCircle,
  BookOpen,
  Check,
  ChevronRight,
  Clock,
  Cloud,
  Copy,
  Cpu,
  Download,
  FileText,
  Folder,
  Frame,
  Globe,
  HelpCircle,
  Image as ImageIcon,
  Laptop,
  List,
  MessagesSquare,
  Minus,
  Moon,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Slash,
  SlidersHorizontal,
  Sparkles,
  Square,
  Store,
  Sun,
  Terminal,
  Trash2,
  Users,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  users: Users,
  plus: Plus,
  search: Search,
  clock: Clock,
  book: BookOpen,
  sparkle: Sparkles,
  folder: Folder,
  send: Send,
  chevron: ChevronRight,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  check: Check,
  terminal: Terminal,
  edit: Pencil,
  cpu: Cpu,
  laptop: Laptop,
  cloud: Cloud,
  pin: Pin,
  share: Share2,
  trash: Trash2,
  copy: Copy,
  refresh: RefreshCw,
  zap: Zap,
  stop: Square,
  x: X,
  minus: Minus,
  clip: Paperclip,
  slash: Slash,
  image: ImageIcon,
  shield: Shield,
  sliders: SlidersHorizontal,
  list: List,
  globe: Globe,
  channels: MessagesSquare,
  alert: AlertCircle,
  download: Download,
  frame: Frame,
  'align-left': AlignLeft,
  doc: FileText,
  question: HelpCircle,
  server: Server,
  shop: Store,
};

export function iconFor(name: string): LucideIcon {
  return ICONS[name] || FileText;
}
